"""One-time setup: test PostgreSQL, write .env, create tables, seed fabrics."""
import getpass
import secrets
import sys
from pathlib import Path
from urllib.parse import quote_plus

import psycopg
from dotenv import load_dotenv

ENV_PATH = Path(__file__).parent / ".env"


def prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or default


def main() -> int:
    print("\n=== Sky Tex — PostgreSQL setup ===\n")

    db_name = prompt("Database name you created in pgAdmin", "fabrics")
    user = prompt("PostgreSQL username", "postgres")
    password = getpass.getpass("PostgreSQL password (postgres user): ")
    if not password:
        print("Password is required.")
        return 1

    host = prompt("Host", "localhost")
    port = prompt("Port", "5432")

    database_url = (
        f"postgresql://{quote_plus(user)}:{quote_plus(password)}"
        f"@{host}:{port}/{quote_plus(db_name)}"
    )

    print("\nConnecting...")
    try:
        with psycopg.connect(database_url, connect_timeout=8) as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT version()")
                cur.fetchone()
        print("Connected successfully.")
    except Exception as exc:
        print(f"Connection failed: {exc}")
        print("\nTips:")
        print("- Use the same password you enter in pgAdmin for PostgreSQL 18")
        print("- Database name must match exactly (case-sensitive)")
        return 1

    secret_key = secrets.token_hex(32)
    admin_user = prompt("Website admin username", "Pratham")
    admin_pass = getpass.getpass("Website admin password (for /admin.html): ")
    if not admin_pass:
        admin_pass = "Lollipop069"
        print("Using default admin password from README (change it after login).")

    env_text = f"""# Auto-generated by setup_local.py — do not commit to git.

DATABASE_URL={database_url}

SECRET_KEY={secret_key}

ADMIN_USERNAME={admin_user}
ADMIN_PASSWORD={admin_pass}

FLASK_DEBUG=1
"""
    ENV_PATH.write_text(env_text, encoding="utf-8")
    print(f"\nWrote {ENV_PATH}")

    load_dotenv(ENV_PATH)
    try:
        from backend.database import init_db
    except ImportError:
        from database import init_db

    print("Creating tables and seed data...")
    init_db()
    print("\nDone! Tables are ready with sample fabrics.")
    print("Start the site:  python app.py")
    print("Then open:       http://127.0.0.1:5000/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
